"""
Paper Engine Domain Models (v2.0).
File-System Source of Truth.
"""
from enum import Enum
from typing import Dict, Optional, List

from pydantic import BaseModel, Field

from app.core.definitions import BlockType
from app.domain.unified_io import ContentBlock


class FileType(str, Enum):
    LATEX_MAIN = "LATEX_MAIN"       # Immutable root (main.tex)
    LATEX_PART = "LATEX_PART"       # Mutable content (sections/*.tex)
    STYLE = "STYLE"                 # Immutable style (easymcm.sty)
    ASSET = "ASSET"                 # Binary (img/*.png)
    BUILD_LOG = "BUILD_LOG"         # Transient logs
    PDF_OUTPUT = "PDF_OUTPUT"       # Result (main.pdf)
    SCRIPT = "SCRIPT"               # build.py


class WritingTask(BaseModel):
    """
    [NEW] A discrete unit of writing work.
    Generated by the Scaffolder, executed by the Manager via LLM.
    """
    target_path: str           # e.g., "sections/01_intro.tex"
    title: str                 # e.g., "Introduction"
    instruction: str           # e.g., "Summarize the problem..."
    placeholder: str = "% <CONTENT_PLACEHOLDER>"
    context_tags: List[str] = Field(default_factory=list)


class VirtualFile(BaseModel):
    """
    Atomic unit of the file system snapshot.
    Represents the state of a file in the Sandbox/Editor.
    """
    path: str
    content: Optional[str] = None
    blob_hash: Optional[str] = None
    file_type: FileType = FileType.LATEX_PART
    is_readonly: bool = False
    mime_type: str = "text/plain"

    def to_content_block(self) -> ContentBlock:
        """Convert a VirtualFile into a Unified IO ContentBlock."""
        if self.content is not None:
            block_type = BlockType.CODE if self.file_type == FileType.SCRIPT else BlockType.MARKDOWN
            return ContentBlock(
                type=block_type,
                label=self.path,
                content=self.content,
                data_key=f"path:{self.path}",
                meta={
                    "filename": self.path,
                    "readonly": self.is_readonly,
                    "mime_type": self.mime_type
                }
            )
        return ContentBlock(
            type=BlockType.FILE,
            label=self.path.split("/")[-1],
            meta={
                "blob_hash": self.blob_hash,
                "filename": self.path,
                "mime_type": self.mime_type,
                "readonly": self.is_readonly
            }
        )


class BuildReport(BaseModel):
    """Result of a compilation cycle."""
    success: bool
    exit_code: int = 0
    logs: str = ""
    error_summary: Optional[str] = None


class CompileStatus(str, Enum):
    IDLE = "IDLE"
    COMPILING = "COMPILING"
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"


class PaperWorkspace(BaseModel):
    """
    The Aggregate Root for Phase 3.
    Replaces the old 'PaperDOM' tree structure.
    """
    project_id: str
    files: Dict[str, VirtualFile] = Field(default_factory=dict)

    compile_status: CompileStatus = CompileStatus.IDLE
    last_build_report: Optional[BuildReport] = None
    last_build_log: str = ""
    pdf_url: Optional[str] = None

    def get_file(self, path: str) -> Optional[VirtualFile]:
        return self.files.get(path)

    def get_text_content(self, path: str) -> str:
        f = self.files.get(path)
        return f.content if f and f.content else ""

    def get_main_tex(self) -> Optional[VirtualFile]:
        """Get the main.tex file if it exists."""
        for f in self.files.values():
            if f.file_type == FileType.LATEX_MAIN:
                return f
        return self.files.get("main.tex")
