"use client";
import { useEffect, useCallback, useRef } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useSignal } from "@/app/context/SignalContext";
import { toast } from "sonner";

export function useLiveWorkflowSync(projectId: string) {
  const queryClient = useQueryClient();
  const { on, isConnected } = useSignal();
  
  // Track mount time to establish a temporal boundary for what counts as "Live" vs "History"
  const mountTime = useRef(Date.now());
  
  // [FIX] Removed throttle for Critical State Events.
  // NODE_UPDATE and TIMELINE_UPDATE signal strict state transitions (e.g. Execution Finished).
  // They must ALWAYS trigger a re-fetch to ensure UI consistency (Artifacts/Logs availability).
  // Throttling here caused "Race Condition" where a Status update would block the Data update
  // if they arrived within 500ms of each other.

  const handleCriticalUpdate = useCallback((data: any) => {
      // 1. Refresh Global Topology (Project Structure)
      // Necessary for Sidebars and Global Beacons to update status colors.
      queryClient.invalidateQueries({ queryKey: ["projects", projectId], exact: true });

      // 2. Refresh Node Workspace (Data/Blocks)
      // This is the most critical update. It fetches the new artifacts and logs 
      // generated by the execution that just finished.
      if (data.node_id) {
         queryClient.invalidateQueries({ queryKey: ["projects", projectId, "nodes", data.node_id] });
      }
      
      // 3. Refresh Timeline (History Versions)
      // Ensures the TimeRail shows the new version capsule.
      queryClient.invalidateQueries({ queryKey: ["projects", projectId, "timeline"] });
  }, [queryClient, projectId]);

  useEffect(() => {
    if (!projectId || !isConnected) return;
    
    // Reset mount time on reconnect
    mountTime.current = Date.now();

    // Listen to High-Priority Control Events
    // These events represent "Checkpoints" in the lifecycle, not continuous streams.
    const unsubNode = on("NODE_UPDATE", handleCriticalUpdate);
    const unsubTimeline = on("TIMELINE_UPDATE", handleCriticalUpdate);
    // NODE_STATUS might happen frequently (e.g. Drafting -> Reviewing), but it's critical for UI state machine.
    const unsubStatus = on("NODE_STATUS", handleCriticalUpdate);
    
    const unsubError = on("ERROR", (d: any) => {
        // =========================================================================
        // [CRITICAL FIX] Ghost Error Prevention (Double Insurance)
        // The backend now filters historical ERROR events in Redis Replay.
        // However, as a failsafe against clock drift or infrastructure edge cases, 
        // we ignore any error timestamped more than 5 seconds before page load.
        // =========================================================================
        const driftBufferMs = 5000;
        if (d.timestamp && (d.timestamp < mountTime.current - driftBufferMs)) {
            console.debug("Filtered out stale historical error:", d.message);
            return;
        }
        toast.error(d.message);
    });

    return () => { 
        unsubNode(); 
        unsubTimeline(); 
        unsubStatus();
        unsubError(); 
    };
  }, [projectId, isConnected, on, handleCriticalUpdate]);
}
