"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Box, User, Lock, Ticket, ArrowRight, CheckCircle, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";

const REQUIRE_INVITE_CODE = process.env.NEXT_PUBLIC_REQUIRE_INVITE_CODE === "true";
const ALLOW_PUBLIC_REGISTRATION = process.env.NEXT_PUBLIC_ALLOW_PUBLIC_REGISTRATION !== "false";

// Terms Content Constant
const TERMS_CONTENT = `MM-Agent / MCM Academic Modeling Agent
Terms of Use, Privacy Notice, and Research Data Consent


Effective Date: January 21, 2026
Product Name: MM-Agent / MCM Academic Modeling Agent (the "Service")
Provider: USAIL Team, The Hong Kong University of Science and Technology (Guangzhou) ("we", "us", or "our")

Before using the Service, please read and fully understand this Terms of Use, Privacy Notice, and Research Data Consent (the "Agreement"). By clicking "Agree/Accept" or by accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by this Agreement. If you do not agree, please do not use the Service.

1. Service Nature and Scope
The Service is an intelligent assistant tool intended for academic and learning purposes, designed to support mathematical modeling, data analysis, academic writing, and related research training.
All outputs generated by the Service are provided for reference only and do not constitute any guarantee, commitment, or professional advice of any kind (including but not limited to guarantees of competition awards, academic outcomes, or legal/medical/financial advice).
You understand and agree that model outputs may contain errors, omissions, outdated information, or inappropriate content. You should exercise independent judgment and assume full responsibility for any consequences arising from your use of the Service.

1.4 Term and Termination (Important)
Service availability period: We will provide the Service only during the period from January 30, 2026 to March 1, 2026. After the period ends, we may shut down servers and discontinue the Service.
User responsibility for data retention: You should export, back up, and properly store any data or content you need within the service period. After the Service expires and is shut down, you may no longer be able to access chat history, uploaded data, or generated results, and we do not guarantee that any data can be recovered or provided.
We may, within a reasonable scope, adjust, suspend, or terminate part or all of the Service due to system maintenance, compliance requirements, security risks, resource constraints, force majeure, or other reasons. Where practicable, we will provide notice via the Service page.

2. Eligibility and Compliant Use
You confirm that you have full civil capacity. If you are a minor, you should use the Service with the consent and guidance of your guardian.
You agree to comply with applicable laws and regulations and all relevant academic integrity standards and requirements of competitions/courses/schools (including MCM/ICM rules). You are solely responsible for your conduct and for any content you create or submit through your use of the Service.
You must not use the Service to engage in illegal or non-compliant activities, including but not limited to infringement, cheating, malicious attacks, distribution of harmful content, or uploading illegally obtained data.

2.4 Account Use and Non-Commercial Use (Including Enforcement)
Account personal-use only: Your Service account and access rights are limited to your personal use for learning and academic research purposes. Without our prior written consent, you may not transfer, lend, rent, share, resell, or otherwise allow any third party to use your account or access credentials (including but not limited to usernames, passwords, verification codes, invitation codes, links, keys/tokens, etc.).
Prohibited commercial use: You may not use the Service for any commercial purpose, including but not limited to paid ghostwriting/outsourcing, training and course sales, commercial consulting, providing paid services to third parties, bulk generation and sale of content, redistribution, or sublicensing of the Service's capabilities.
Violation handling and liability: If we discover or reasonably suspect that you have engaged in any of the above conduct or other abuse, we may take measures without further notice, including but not limited to restricting features, suspending access, terminating the Service, banning accounts/devices/IP addresses, or refusing future service. You shall bear all consequences and losses arising therefrom. We reserve the right to pursue legal liability and seek compensation for losses in accordance with law (including reasonable expenses incurred for rights protection).
Account security obligation: You are responsible for safeguarding your account information and for all activities conducted under your account. Unless you can prove that actions were caused by our systems, all actions under your account will be deemed to have been performed by you.

3. Scope of Data Collection (Data You May Provide / We May Log)
To provide the Service, ensure security, improve the system, and conduct academic research, we may collect or process the following data, depending on your actual usage:
Data you provide proactively: text prompts, modeling descriptions, code snippets, uploaded files/datasets (if any), conversation content, etc.
Usage and log information: access time, operation records, error logs, device/browser information, IP address (or coarse-grained location information), etc.
Feedback data: your ratings of outputs, correction feedback, survey responses (if any).
Important reminder: Please do not upload or enter data that you do not wish to be recorded or used for research, especially sensitive personal information such as government ID numbers, bank card numbers, precise residential addresses, account passwords, medical information, non-public commercial secrets, or data subject to confidentiality obligations. If you choose to upload such information, you assume the associated risks.

4. Purposes of Data Use (Primarily Academic)
We process your data primarily for the following purposes:
Service provision and maintenance: generating responses, troubleshooting, improving performance, and ensuring security.
Academic research and system improvement: researching methods for LLM agents in modeling/alignment/reasoning, performing statistical analysis, error analysis, evaluation, and iterative optimization.
Academic publications and dissemination: research findings may be presented in papers, reports, and presentations, typically in aggregated statistics, anonymized examples, or processed excerpts.

5. Consent to Use Research Data (Key Terms)
You agree that data you submit and interaction records generated during your use of the Service may be used for academic research purposes, including but not limited to model evaluation, algorithm improvement, paper writing, and academic exchange.
We will make reasonable efforts to de-identify and/or anonymize research data and will avoid disclosing information that could identify you when publicly publishing or presenting.
You understand that anonymization is not zero-risk. We will adopt reasonable technical and organizational measures to reduce risk, but cannot guarantee complete prevention of all security incidents.
If you do not agree to the use of your data for research, you may choose not to use the Service; or, where supported, you may apply to opt out of research use via the official channels described in Section 11, and we will handle your request to the extent feasible.

6. Data Sharing and Disclosure
We do not sell your personal data to third parties in principle.
We may share data in limited circumstances to enable the Service or conduct research, including:
• Sharing necessary data with infrastructure, storage, or computing service providers, who must assume confidentiality and security obligations.
• Where disclosure is required by laws, regulations, judicial decisions, or regulatory authorities.
• To protect our or users' legitimate rights and interests, and to handle security incidents and abusive behavior.
In the event of a merger, reorganization, or asset transfer, we will make reasonable efforts to require the recipient to remain bound by this Agreement or provide protection no less than that set forth herein.

7. Data Storage, Retention Period, and Deletion
We will retain data for the period necessary to achieve the purposes described in this Agreement, or as required by applicable laws and regulations.
You may request deletion or export via the official channels described in Section 11. We will handle such requests based on technical feasibility, compliance requirements, and research integrity needs (certain logs/backups may not be immediately or fully deletable).
For anonymized or aggregated data used for academic statistics, it may be impossible to trace back and delete data at the level of a specific user.
Service expiration data cleanup notice: Given that the Service is available for a limited period (see Section 1.4), after the service period ends and servers are shut down, we may clean up or decommission server data within a reasonable period. You should complete any necessary exports and backups within the service period. We are not responsible for any data loss or inaccessibility resulting from your failure to save data in time.

8. Information Security Measures
We will implement reasonable security measures (such as access controls, encrypted transmission, permission management, and auditing) to protect data security. However, you understand that any system carries risks, and we do not assume liability beyond what is permitted by law for losses caused by force majeure or third-party factors.

9. Intellectual Property and License
Intellectual property rights in the Service, including its system, model invocation logic, interface, and documentation, belong to us or the relevant rights holders.
You retain any rights you lawfully hold in your input content. However, you grant us a license to process your input content and derivative logs within the scope of the purposes stated in this Agreement.
Content generated by the Service may include third-party knowledge or similar expressions. You should independently verify citations and compliant use to avoid infringement and academic misconduct.

10. Disclaimers and Limitation of Liability (Key Risk Provisions)
The Service is provided on an "as is" and "as available" basis. We make no express or implied warranties regarding continuity, accuracy, completeness, or fitness for a particular purpose.
You understand and agree that you assume full responsibility for your use of the Service and all consequences. To the maximum extent permitted by law, we are not liable (or are liable only to a limited extent) for any direct or indirect losses arising from your use of or inability to use the Service, including but not limited to grades/competition results/data loss/reputational damage/commercial losses.
If you use the Service for competition submissions, academic papers, or production environments, you must independently conduct sufficient verification, compliance review, and risk assessment.
The Service may include external links or third-party tools/model components, and we are not responsible for third-party conduct or content.

11. Contact Information and Exercising Your Rights
If you have any questions about this Agreement or data processing, wish to opt out of research data use, request deletion/export of data, or report abuse, you may contact us through the official channels announced on the Service page. You may also submit feedback through the project team's GitHub page (e.g., Issue/Discussion).
Organization/Team: USAIL Team, The Hong Kong University of Science and Technology (Guangzhou)
Project Team Link (GitHub): https://github.com/usail-hkust
We will respond and handle your request within a reasonable period.

12. Updates to This Agreement
We may update this Agreement from time to time. Before and after a new version takes effect, we will provide a prominent notice on the Service page. Your continued use of the Service will be deemed acceptance of the updated Agreement.

Click-to-Agree Statement (Recommended to Place Above the Button)
I have read and understood the "MM-Agent / MCM Academic Modeling Agent - Terms of Use, Privacy Notice, and Research Data Consent", agree to all of its terms, and consent to the processing and de-identified use of my inputs and interaction data for academic research purposes.
Buttons: [Agree and Continue] / [Disagree, Exit]

Prominent reminder (optional, suggested for registration page): Service ends on 2026/03/01. Please export and back up your data in time.`;

export default function RegisterPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [inviteCode, setInviteCode] = useState("");
  const [agreed, setAgreed] = useState(false);
  
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!agreed) {
        setError("You must agree to the terms to continue.");
        return;
    }
    
    setError("");
    setLoading(true);

    try {
      const API_BASE = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:8000/api/v1";
      
      const res = await fetch(`${API_BASE}/auth/register`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            email,
            password,
            invite_code: REQUIRE_INVITE_CODE ? inviteCode : "",
            terms_agreed: agreed
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.detail || "Registration failed");
      }

      setSuccess(true);
      // Optional: Auto login? For now, redirect to login page for UX flow
      setTimeout(() => {
          router.push("/login");
      }, 2000);

    } catch (err: any) {
      setError(err.message || "Registration failed.");
    } finally {
      setLoading(false);
    }
  };

  if (success) {
      return (
        <div className="min-h-screen bg-gradient-to-br from-[#f3f6ff] via-white to-[#f7f5ff] flex items-center justify-center p-4">
            <div className="bg-white p-8 rounded-2xl shadow-xl border border-gray-100 w-full max-w-md text-center space-y-6 animate-in fade-in zoom-in duration-300">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
                    <CheckCircle className="w-8 h-8 text-green-600" />
                </div>
                <h2 className="text-2xl font-bold text-gray-900">Account Created!</h2>
                <p className="text-gray-500">Redirecting to login...</p>
            </div>
        </div>
      );
  }

  if (!ALLOW_PUBLIC_REGISTRATION) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-[#f3f6ff] via-white to-[#f7f5ff] flex items-center justify-center p-4">
        <div className="bg-white p-8 rounded-2xl shadow-xl border border-gray-100 w-full max-w-md text-center space-y-5">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-black text-white mx-auto">
            <Box className="w-6 h-6" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Registration Disabled</h1>
          <p className="text-sm text-gray-500">
            This local deployment uses pre-created accounts only. Sign in with the default local account shown on the login page.
          </p>
          <button
            type="button"
            onClick={() => router.push("/login")}
            className="w-full bg-black text-white py-2.5 rounded-lg font-bold hover:bg-gray-800 transition-colors"
          >
            Back to Login
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f3f6ff] via-white to-[#f7f5ff] flex items-center justify-center p-4">
      <div className="bg-white p-6 sm:p-8 rounded-2xl shadow-xl border border-gray-100 w-full max-w-md space-y-5 max-h-[90vh] overflow-y-auto">
        <div className="text-center space-y-2 shrink-0">
          <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-black text-white mb-4">
            <Box className="w-6 h-6" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900">Create Account</h1>
          <p className="text-gray-500 text-sm">Join the MM Agent Platform</p>
        </div>

        <form onSubmit={handleRegister} className="space-y-5">
          {/* Email */}
          <div className="relative">
            <User className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-gray-400 transition-all"
              placeholder="Email Address"
              required
            />
          </div>

          {/* Password */}
          <div className="relative">
            <Lock className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-gray-400 transition-all"
              placeholder="Password (min 8 chars)"
              required
              minLength={8}
            />
          </div>

          {REQUIRE_INVITE_CODE && (
            <div className="relative">
              <Ticket className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
              <input
                type="text"
                value={inviteCode}
                onChange={(e) => setInviteCode(e.target.value.toUpperCase())}
                className="w-full pl-10 pr-4 py-2.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-black/5 focus:border-gray-400 transition-all font-mono uppercase tracking-wide"
                placeholder="Invitation Code"
                required
              />
            </div>
          )}

          {/* Terms Box */}
          <div className="bg-slate-50 border border-slate-200 rounded-lg p-3 text-xs text-slate-600 leading-relaxed font-mono max-h-32 overflow-y-auto shrink-0">
             <div className="whitespace-pre-wrap">{TERMS_CONTENT}</div>
          </div>

          {/* Agreement Checkbox */}
          <label className="flex items-start gap-3 cursor-pointer group shrink-0">
             <div className="relative flex items-center shrink-0 mt-0.5">
                <input 
                    type="checkbox" 
                    className="peer sr-only"
                    checked={agreed}
                    onChange={(e) => setAgreed(e.target.checked)}
                />
                <div className="w-5 h-5 border-2 border-slate-300 rounded peer-checked:bg-black peer-checked:border-black transition-all"></div>
                <CheckCircle className="absolute w-3.5 h-3.5 text-white opacity-0 peer-checked:opacity-100 top-0.5 left-0.5 pointer-events-none" />
             </div>
             <span className={cn("text-xs pt-0.5 select-none transition-colors", agreed ? "text-slate-900" : "text-slate-500")}>
                I have read and understood the Terms of Use, Privacy Notice, and Research Data Consent.
             </span>
          </label>

          {error && (
            <div className="flex items-start gap-2 text-red-600 text-xs bg-red-50 p-3 rounded-lg border border-red-100 shrink-0">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <div className="space-y-3 pt-2 shrink-0">
            <button
              type="submit"
              disabled={loading || !agreed}
              className="w-full bg-black text-white py-2.5 rounded-lg font-bold hover:bg-gray-800 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading ? "Creating Account..." : "Sign Up"}
              {!loading && <ArrowRight className="w-4 h-4" />}
            </button>
            
            <button
              type="button"
              onClick={() => router.push("/login")}
              className="w-full text-gray-500 hover:text-gray-800 text-sm font-medium py-2 transition-colors"
            >
              Already have an account? Log in
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
